"use client"
import { useEffect,useState } from "react"
import { createClient } from "@/lib/supabase/client"
type Product={id:string;name:string;description:string;price_cents:number;image_path:string|null;category:string;inventory:number;slug:string}
const furnitureFallbacks=["/images/sofa.png","/images/product-2.png","/images/product-3.png"]
const fallbackProducts:Product[]=[
 {id:"demo-sofa",name:"Modern Lounge Chair",description:"A comfortable statement piece designed for relaxed living rooms.",price_cents:850000,image_path:"/images/sofa.png",category:"Living Room",inventory:12,slug:"modern-lounge-chair"},
 {id:"demo-accent",name:"Premium Accent Chair",description:"Add character and comfort with a beautifully upholstered accent chair.",price_cents:1250000,image_path:"/images/product-2.png",category:"Living Room",inventory:8,slug:"premium-accent-chair"},
 {id:"demo-office",name:"Ergonomic Office Chair",description:"Comfortable support for focused work, study, and creative sessions.",price_cents:1500000,image_path:"/images/product-3.png",category:"Office",inventory:10,slug:"ergonomic-office-chair"},
]
export default function Shop(){const [products,setProducts]=useState<Product[]>(fallbackProducts);const [query,setQuery]=useState("");const [category,setCategory]=useState("All");useEffect(()=>{let active=true;createClient().from("products").select("*").eq("active",true).order("created_at").then(({data,error})=>{if(!active||error||!data?.length)return;if(active)setProducts(data.map((p,index)=>({...p,image_path:p.image_path?.includes("bowl")?furnitureFallbacks[index%furnitureFallbacks.length]:p.image_path||furnitureFallbacks[index%furnitureFallbacks.length]})))});return()=>{active=false}},[]);const filtered=products.filter(p=>(category==="All"||p.category===category)&&`${p.name} ${p.description}`.toLowerCase().includes(query.toLowerCase()));return <main><div className="shell page-title"><div className="eyebrow">Northstar collection</div><h1>Shop furniture</h1><p>Pieces with a point of view, made for the way you live.</p></div><section className="section"><div className="shell"><div className="toolbar"><input className="input" placeholder="Search furniture" value={query} onChange={e=>setQuery(e.target.value)}/><select className="input" value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{Array.from(new Set(products.map(p=>p.category))).map(c=><option key={c}>{c}</option>)}</select></div><div className="products">{filtered.map((p,index)=><article className="product-card" key={p.id}><img src={p.image_path||furnitureFallbacks[index%furnitureFallbacks.length]} alt={p.name}/><h3>{p.name}</h3><p>{p.description}</p><p className="price">KSh {(p.price_cents/100).toLocaleString()}</p><button className="btn btn-primary" onClick={()=>{const cart=JSON.parse(sessionStorage.getItem("northstar-cart")||"[]");const found=cart.find((i:{id:string})=>i.id===p.id);if(found)found.quantity+=1;else cart.push({...p,quantity:1});sessionStorage.setItem("northstar-cart",JSON.stringify(cart));window.location.assign("/cart")}}>Add to cart</button></article>)}</div>{!filtered.length&&<p className="notice">No furniture matched your search.</p>}</div></section></main>}
